---
- name: Run all-your-base-image
  hosts: hosts
  tasks:
    - name: build container
      docker_container:
        name: all-your-base
        image: roundkubik/docker_id:latest
        state: started
        recreate: yes
        pull: true
        ports:
          - "20:20"
        exposed_ports:
          - "20"
        detach: true
        container_default_behavior: compatibility
...
